### ISSUE TITLE
parts list quantity question

### ISSUE THREAD

**Issue by MatthewNinety** [TheRobotStudio/SO-ARM100#15]
In your parts list, it says the unit price for servos is $14.  But when I click the US alibaba link that you have listed for the servos, it says there are 6 servos per batch, and the total price is about $17 per batch, with about $12 in shipping.
That means the total price for 12 servos (17*2)  and shipping is about $50, which comes out to about $2 per servo.
This is a significant difference.  Did I make a mistake?

**Comment by TheRobotStudio** [comment]
If you follow it through that 1 piece should add 6 servos to the cart and an adaptor board, now 15USD each plus tax of about 17USD.

To France where I am I get free shipping presently so the total is 103EUR.

**Comment by MatthewNinety** [comment]
Thanks that solved it! I act like I've never gone shopping before :)
