### ISSUE TITLE
Alibaba link to STS3215 Servo shows "This product is no longer available."

### ISSUE THREAD

**Issue by ashwinvk94** [TheRobotStudio/SO-ARM100#6]
![Screenshot from 2024-10-02 08-11-38](https://github.com/user-attachments/assets/67e9ce7f-89fd-47ef-8369-c25ae039966e)

**Comment by ramkumarkoppu** [comment]
Looks it is out of stock,  it may be bit more expensive to buy from other suppliers like this https://uk.robotshop.com/products/magnetic-encoding-servo-sts3215-74v-19kgcm

**Comment by TheRobotStudio** [comment]
I'm not sure why that link has suddenly died. The servos are definitely in stock.

**Comment by EvanMath** [comment]
Hi everyone,

I found that ordering STS3215 from AliExpress (https://www.aliexpress.com/item/1005007693922437.html?spm=a2g0o.productlist.main.3.18be16c8A3Q2oj&algo_pvid=f7129a0f-9676-4ec2-907a-b925e3f5ea45&utparam-url=scene%3Asearch%7Cquery_from%3A) is cheaper as the transfer costs seem to be much less. At least for Greece where I am located. And it is the same shop in both cases.
